---
api_token: 

account_id: 

org_id: 

project_id: 

token_name: 

delegate_name: 

# Extra variables to override the default value
# NOTE: Only modify if required and for production deployments

# Defaults to LAPTOP. Other available options "SMALL" "MEDIUM" "LARGE"
delegate_size:

# Defaults to ~/.kube/config
kubeconfig:
